on:
  push:
    branches: ['main', 'develop']
    paths-ignore:
      - '**/**.md'

  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: helpdesk-api
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '18.x'
  MONGODB_VERSION: '5.0'

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ env.MONGODB_VERSION }}
          mongodb-replica-set: helpdesk
          mongodb-port: 27017

      - name: Install dependencies
        run: npm install

      - name: Run end-to-end tests
        run: npm run test:e2e;exit 0
        env:
          NODE_ENV: test
          CI: true

  #   - name: Upload artifact for deployment job
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: node-app
  #       path: .

  # deploy:
  #   permissions:
  #     contents: none
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: 'Development'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #   steps:
  #   - name: Download artifact from build job
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: node-app

  #   - name: 'Deploy to Azure WebApp'
  #     id: deploy-to-webapp
  #     uses: azure/webapps-deploy@v2
  #     with:
  #       app-name: ${{ env.AZURE_WEBAPP_NAME }}
  #       publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #       package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
